spring:
  cloud:
    gateway:
      routes:
        - id: bing-route
          uri: https://cn.bing.com
          predicates:
            - name:  Path
              args:
                patterns: /search
            - name:  Query
              args:
                param: q
                regexp: haha
            - name: Vip
              args:
                param: user
                value: hty
        - id: order-route
          uri: lb://service-order
          predicates:
            - name: Path
              args:
                patterns: /api/order/**
                matchSingleSegment: true
          filters:
            - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
          order: 1
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
      default-filters:
        - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
